import type { Product } from '@/lib/types';

export const products: Product[] = [
  {
    id: 'classic-white-tee',
    name: 'Classic White Tee',
    brand: 'Koksi Kok',
    description: 'A timeless wardrobe staple. Made from 100% premium cotton for a soft and comfortable fit.',
    price: 29.99,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    category: 'Clothing',
    imageIds: ['classic-white-tee', 'classic-white-tee-2', 'classic-white-tee-3', 'classic-white-tee-hover'],
    material: '100% Cotton',
    countryOfOrigin: 'Egypt',
  },
  {
    id: 'slim-fit-jeans',
    name: 'Slim Fit Jeans',
    brand: 'Koksi Kok',
    description: 'Modern slim fit jeans crafted from stretch-denim for all-day comfort. A versatile piece for any occasion.',
    price: 69.99,
    originalPrice: 89.99,
    sizes: ['28', '30', '32', '34', '36'],
    category: 'Clothing',
    imageIds: ['slim-fit-jeans', 'slim-fit-jeans-2', 'slim-fit-jeans-hover'],
    material: 'Stretch Denim',
    countryOfOrigin: 'Turkey',
  },
  {
    id: 'leather-biker-jacket',
    name: 'Leather Biker Jacket',
    brand: 'Koksi Kok',
    description: 'An iconic biker jacket made from genuine sheepskin leather. Features asymmetrical zip and silver-tone hardware.',
    price: 299.99,
    sizes: ['S', 'M', 'L'],
    category: 'Clothing',
    imageIds: ['leather-biker-jacket', 'leather-biker-jacket-hover'],
    material: 'Genuine Leather',
    countryOfOrigin: 'Turkey',
  },
  {
    id: 'cashmere-sweater',
    name: 'Cashmere Sweater',
    brand: 'Koksi Kok',
    description: 'Experience ultimate luxury with our 100% cashmere sweater. Incredibly soft, warm, and stylish.',
    price: 119.99,
    originalPrice: 149.99,
    sizes: ['S', 'M', 'L', 'XL'],
    category: 'Clothing',
    imageIds: ['cashmere-sweater', 'cashmere-sweater-hover'],
    material: '100% Cashmere',
    countryOfOrigin: 'China',
  },
  {
    id: 'suede-chelsea-boots',
    name: 'Suede Chelsea Boots',
    brand: 'Koksi Kok',
    description: 'Elegant and versatile Chelsea boots in a rich brown suede. Perfect for smart-casual looks.',
    price: 179.99,
    sizes: ['8', '9', '10', '11', '12'],
    category: 'Shoes',
    imageIds: ['suede-chelsea-boots', 'suede-chelsea-boots-hover'],
    material: 'Suede',
    countryOfOrigin: 'Portugal',
  },
  {
    id: 'minimalist-sneakers',
    name: 'Minimalist Sneakers',
    brand: 'Koksi Kok',
    description: 'Clean and simple white leather sneakers. The perfect go-to shoe for any casual outfit.',
    price: 99.99,
    originalPrice: 119.99,
    sizes: ['7', '8', '9', '10', '11', '12'],
    category: 'Shoes',
    imageIds: ['minimalist-sneakers', 'minimalist-sneakers-hover'],
    material: 'Leather',
    countryOfOrigin: 'Vietnam',
  },
  {
    id: 'tailored-chino-shorts',
    name: 'Tailored Chino Shorts',
    brand: 'Koksi Kok',
    description: 'Smart and comfortable chino shorts for warmer days. Made with a hint of stretch for the perfect fit.',
    price: 59.99,
    sizes: ['30', '32', '34', '36'],
    category: 'Clothing',
    imageIds: ['tailored-chino-shorts', 'tailored-chino-shorts-hover'],
    material: 'Cotton Blend',
    countryOfOrigin: 'Egypt',
  },
  {
    id: 'linen-button-down',
    name: 'Linen Button-Down',
    brand: 'Koksi Kok',
    description: 'Stay cool and stylish with this breathable linen shirt. A summer essential.',
    price: 79.99,
    sizes: ['S', 'M', 'L', 'XL'],
    category: 'Clothing',
    imageIds: ['linen-button-down', 'linen-button-down-hover'],
    material: '100% Linen',
    countryOfOrigin: 'Egypt',
  },
  {
    id: 'wool-overcoat',
    name: 'Wool Overcoat',
    brand: 'Koksi Kok',
    description: 'A sophisticated single-breasted overcoat made from a rich wool blend. Perfect for layering in cold weather.',
    price: 349.99,
    sizes: ['S', 'M', 'L', 'XL'],
    category: 'Clothing',
    imageIds: ['wool-overcoat', 'wool-overcoat-hover'],
    material: 'Wool Blend',
    countryOfOrigin: 'Turkey',
  },
  {
    id: 'leather-loafers',
    name: 'Leather Loafers',
    brand: 'Koksi Kok',
    description: 'Classic penny loafers crafted from full-grain leather. A timeless addition to your formal footwear collection.',
    price: 199.99,
    sizes: ['8', '9', '10', '11'],
    category: 'Shoes',
    imageIds: ['leather-loafers', 'leather-loafers-hover'],
    material: 'Full-Grain Leather',
    countryOfOrigin: 'Portugal',
  },
  {
    id: 'silk-blend-blouse',
    name: 'Silk-Blend Blouse',
    brand: 'Koksi Kok',
    description: 'An effortlessly chic blouse made from a luxurious silk blend. Features a relaxed fit and concealed buttons.',
    price: 129.99,
    sizes: ['XS', 'S', 'M', 'L'],
    category: 'Clothing',
    imageIds: ['silk-blend-blouse', 'silk-blend-blouse-hover'],
    material: 'Silk Blend',
    countryOfOrigin: 'China',
  },
  {
    id: 'high-waisted-trousers',
    name: 'High-Waisted Trousers',
    brand: 'Koksi Kok',
    description: 'Flattering high-waisted trousers with a wide-leg silhouette. Creates a polished and elongated look.',
    price: 99.99,
    sizes: ['XS', 'S', 'M', 'L'],
    category: 'Clothing',
    imageIds: ['high-waisted-trousers', 'high-waisted-trousers-hover'],
    material: 'Polyester Blend',
    countryOfOrigin: 'Vietnam',
  },
];
